### ISSUE TITLE
[request] Option to add column and line

### ISSUE THREAD

**Issue by sassanh** [diegoulloao/nvim-file-location#1]
It would be nice if this plugin also supports generating location with column included like this: `some-directory/another-directory/filename.ext:5:8`

P.S. Before this plugin I used to have these mappings for this purpose:
```lua
vim.keymap.set('', '<leader>C!', '<cmd>let @+="`".expand("%")<cr>', { silent = true })
vim.keymap.set('', '<leader>C@', '<cmd>let @+="`".join([expand("%"), line(".")], ":")<cr>', { silent = true })
vim.keymap.set('', '<leader>C#', '<cmd>let @+="`".join([expand("%"), line("."), col(".")], ":")<cr>', { silent = true })
```
I add a `` ` `` prefix so that I can paste it in Slack and save a keystroke in "backticking" it in Slack.

**Comment by diegoulloao** [comment]
Sure @sassanh, sounds good. I'll work in this during my break.
Not sure about the notation, I'd like to follow a convention. Is it `.ext:5:8` the convention for line and column notation? If not, what about `.ext:5,8` in order to make it more readable?

Let's discuss about this. I'd to hear your thoughts.
Thanks for the request.

**Comment by diegoulloao** [comment]
I can see `:line:col` is the standard, so there is nothing to discuss.
I'll let you know when it be ready 😉

**Comment by diegoulloao** [comment]
PR https://github.com/diegoulloao/nvim-file-location/pull/2

**Comment by diegoulloao** [comment]
@sassanh merged to main.

**Comment by sassanh** [comment]
Thanks!
